<a href="https://colab.research.google.com/github/rozaleenemad/project-OOP-BankSystem--SOLID-/blob/master/AI_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd  # For working with structured data using DataFrames and Series
from sklearn.model_selection import train_test_split   # For splitting the dataset into training and testing sets
from sklearn.linear_model import LogisticRegression    # Import the Logistic Regression classifier from scikit-learn
from sklearn.metrics import accuracy_score             # For calculating the accuracy of the model's predictions

In [5]:
from google.colab import drive  # Used to mount Google Drive in Google Colab to access datasets stored on Drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
load = pd.read_csv("/content/drive/MyDrive/heart .csv") # variable to store dataset
load  # print dataset

,Age,Gender,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin,Result
0,63,1,66,160.0,83,160.0,1.80,0.012,negative
1,20,1,94,98.0,46,296.0,6.75,1.060,positive
2,56,1,64,160.0,77,270.0,1.99,0.003,negative
3,66,1,70,120.0,55,270.0,13.87,0.122,positive
4,54,1,64,112.0,65,300.0,1.08,0.003,negative
...,...,...,...,...,...,...,...,...,...
1326,45,1,85,168.0,104,96.0,1.24,4.250,positive
1327,54,1,58,117.0,68,443.0,5.80,0.359,positive
1328,51,1,94,157.0,79,134.0,50.89,1.770,positive
1329,40,0,75,148.0,73,117.0,3.32,0.008,negative
1330,45,1,72,154.0,67,98.0,16.08,0.010,positive

In [7]:
load.info() # print number of rows , columns , name of columns , datatype of column , missing values and memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1331 entries, 0 to 1330
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1331 non-null   int64
 1   Gender                    1331 non-null   int64
 2   Heart rate                1331 non-null   int64
 3   Systolic blood pressure   1331 non-null   float64
 4   Diastolic blood pressure  1331 non-null   int64
 5   Blood sugar               1331 non-null   float64
 6   CK-MB                     1331 non-null   float64
 7   Troponin                  1331 non-null   float64
 8   Result                    1331 non-null   object
dtypes: float64(4), int64(4), object(1)
memory usage: 93.7+ KB

In [8]:
X = load.drop("Result", axis=1) # delete column of target and store columns of features
y = load["Result"] # store column of target
y # print column of target

0       negative
1       positive
2       negative
3       positive
4       negative
          ...
1326    positive
1327    positive
1328    positive
1329    negative
1330    positive
Name: Result, Length: 1331, dtype: object

In [9]:
y.value_counts() # Shows the number of samples in each class of the target variable

Result
positive    813
negative    518
Name: count, dtype: int64

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Splitting the data into:
# X_train, y_train → Training data (70%)
# X_test, y_test → Test data (30%)
# test_size=0.3 means 30% of the data is for testing
# random_state=42 ensures the split produces the same result every time we run the code

In [11]:
model = LogisticRegression(solver='liblinear', # The appropriate algorithm for training binary classification
                           max_iter=700, # Maximum number of training attempts
                           verbose=1 # Show details during training
                           )
model.fit(X_train, y_train) # The logistic regression model was trained using the training dataset

y_pred = model.predict(X_test) # The trained model is used to predict the target values for the test data

accuracy = accuracy_score(y_test, y_pred)  # Accuracy measures the percentage of correctly predicted samples by the model
print("Accuracy:", accuracy) # To print accuracy

[LibLinear]Accuracy: 0.84